sudo: required
services:
  - docker

before_install:
  - docker --version 
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json # try to use manifests
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json # needed to use docker manifest
  - sudo service docker restart

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset # setup QEMU for cross-builds

script:
  - make qemu
  - make wrap
  - make build

after_success: # these can fail without breaking the build
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make push
  - make manifest